### ISSUE TITLE
Password with special characters doesn't work either escaped or unescaped

### ISSUE THREAD

**Issue by cmurtaugh** [hunyadi/pysqlsync#3]
Passwords with special characters (e.g. `test?password`) break connection string parsing.

Escaping the password (with `urllib.parse.quote_plus()`) fixes parsing, but the value is not unescaped so login fails.

**Comment by hunyadi** [comment]
If you use `pysqlsync.factory.get_parameters(url)`, a `ConnectionParameters` object is constructed from the output of `urlparse`, which handles special characters in every component of the URL. In fact, integration tests have already had `<YourStrong@Passw0rd>` as the password, and they pass. I have now updated the password to `<?YourStrong@Passw0rd>` and they still pass for all supported databases PostgreSQL, MySQL, Oracle and Microsoft SQL Server.

**Comment by hunyadi** [comment]
In order to improve robustness of parsing username and password components of connection string URLs, `unquote` is now being applied to the output of `urlparse` to reverse percent encoding. I chose `unquote` over `unquote_plus` because [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986.html) appears to permit *plus* (and many other special characters) verbatim in username and password. New unit tests have been added with complex use cases. Code has been pushed to the branch `dev`. Thanks for reporting the issue!
